### ISSUE TITLE
PS Update Issue?

### ISSUE THREAD

**Issue by kdavis0723a** [sriehl/PowerSchool-Student-Map#5]
We love this plugin.  Seems to have stopped working (sticking on loading) close to the V 22.9 update.  Is this a known issue or is there another problem?  

Thanks again!

-Kevin

**Comment by sriehl** [comment]
Have you tried the version released this morning? [1.0.5](https://github.com/sriehl/PowerSchool-Student-Map/releases/tag/v1.0.5)

**Comment by kdavis0723a** [comment]
We looked for an update about 15 minutes before you posted!  Yes, it worked.  Thanks so much!.


-- Kevin

Kevin L. Davis
CEO Indiana Charters
317-945-7723



From: Steven Riehl ***@***.***>
Reply-To: sriehl/PowerSchool-Student-Map ***@***.***>
Date: Wednesday, September 28, 2022 at 10:53 AM
To: sriehl/PowerSchool-Student-Map ***@***.***>
Cc: "kevin.davis indianacharters.com" ***@***.***>, Author ***@***.***>
Subject: Re: [sriehl/PowerSchool-Student-Map] PS Update Issue? (Issue #5)


Have you tried the version released this morning? 1.0.5<https://github.com/sriehl/PowerSchool-Student-Map/releases/tag/v1.0.5>
