### ISSUE TITLE
Not Loading/Rendering in PS 24.11.0

### ISSUE THREAD

**Issue by Jessey-DeVaney** [sriehl/PowerSchool-Student-Map#8]
Hello,

Student Map - Version 1.2.0 has stopped working on our hosted instance of PowerSchool that is on version 24.11.0. 

I have tried both fresh sessions of current FireFox and Chrome for MacOS. Any ideas?

Thank you!

**Comment by sriehl** [comment]
I no longer work at a school district, so I'm not able to test this plugin. If you can provide a screenshot of the browser console and any errors, I might be able to take some stabs in the dark.

**Comment by Jessey-DeVaney** [comment]
Alright. I will try getting that this Friday or next Monday. If I can get
authorization, would getting temporary access to our test server be
helpful?
-----
Jessey DeVaney
(314) 825-7739 mobile
jesseydevaney at gmail dot com

Confidentiality Notice: This email message, including any attachments, is
for the sole use of the intended recipient(s), and may contain privileged
or confidential information.  Any unauthorized review, use, disclosure or
distribution is prohibited.

**Comment by Jessey-DeVaney** [comment]
It was a browser issue. It is working fine now by the way.
-----
Jessey DeVaney
(314) 825-7739 mobile
jesseydevaney at gmail dot com

Confidentiality Notice: This email message, including any attachments, is
for the sole use of the intended recipient(s), and may contain privileged
or confidential information.  Any unauthorized review, use, disclosure or
distribution is prohibited.
